{
	"version": 1749718069,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bg-sheet0.png",
		"images/bts-sheet0.png",
		"images/opponent-sheet0.png",
		"images/bullet-sheet0.png",
		"images/redlightgreenlighthowtosheet-sheet0.png",
		"images/playsheet-sheet0.png",
		"images/border_up-sheet0.png",
		"images/particles.png",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/bts fandom - game over.m4a",
		"media/bts fandom - game over.ogg",
		"media/pop sfx.m4a",
		"media/pop sfx.ogg",
		"media/bts fandom - bgm.m4a",
		"media/bts fandom - bgm.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}